### ISSUE TITLE
Empty the results table between BDD test cases

### ISSUE THREAD

**Issue by yx2512** [devops-wishlist-buddies/wishlists#102]
**Describe the bug**
BDD testing on IBM cloud may fail from time to time due to the existing data left over by previous BDD testing.

**To Reproduce**
1. Go to Stage History | Test on IBM cloud
2. Click on any failed test attempts
3. Scroll down to the bottom of the log
4. See some of the cases are failed and some are skipped

**Expected behavior**
All the test cases should pass

**Comment by ntlz** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/wishlists-614df33bb025e9001866fedf/issues/devops-wishlist-buddies/wishlists/102?planning-poker) with ZenHub @Fivetoes @jiuliwei @XinyuC97 @yx2512 @ZX-WANG
