### ISSUE TITLE
Deploy the app to the cloud

### ISSUE THREAD

**Issue by ntlz** [devops-wishlist-buddies/wishlists#12]
**As a** service provider
**I need** my code to run on the cloud
**So that** users can get access to my service

**Details & Assumptions:** 
* We will deploy to IBM cloud.
* We wish push manually just to make sure it works in IBM Cloud

**Acceptance Criteria:**

```gherkin
Given bare IBM Cloud account
When I push the application to the cloud instance
Then I can follow the provided URL and use Wishlists API
```

**Comment by yx2512** [comment]
added more details to the body of this issue

**Comment by ntlz** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/wishlists-614df33bb025e9001866fedf/issues/devops-wishlist-buddies/wishlists/12?planning-poker) with ZenHub @Fivetoes @jiuliwei @XinyuC97 @yx2512 @ZX-WANG

**Comment by ntlz** [comment]
Changed SP estimate based on Sprint 2 planning meeting.
