### ISSUE TITLE
Add functionality to rename a wishlist

### ISSUE THREAD

**Issue by ntlz** [devops-wishlist-buddies/wishlists#4]
**As a** user
**I need** the ability to rename my wishlist
**So that** I can have more informative names to navigate the set of wishlists

**Details & Assumptions:** 
* The name of a wishlist can not be empty or be the same as other wishlists
* Update the data in database based on wishlist_id
* PUT   /wishlists/<wishlist_id> {name: 'new-name'}

**Acceptance Criteria:**

```gherkin
Given a wishlist
When I make a rename API call via a URL
Then I should get back a wishlist with a changed name
```

**Comment by ntlz** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/wishlists-614df33bb025e9001866fedf/issues/devops-wishlist-buddies/wishlists/4?planning-poker) with ZenHub @Fivetoes @jiuliwei @XinyuC97 @yx2512 @ZX-WANG

**Comment by yx2512** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/27b643c6-9a70-4eea-abde-faef8f7042e9?env_id=ibm:yp:us-south "nyu-wishlist-service-fall2103"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/659061bf-cc38-4631-83b1-de6b76a17d27 "nyu-wishlist-service-fall2103") deployed [wishlists](https://github.com/devops-wishlist-buddies/wishlists/releases/tag/deploy-ibm-yp-us-south-nyu-wishlist-service-fall2103-prod-20211206-185611 "deploy-ibm-yp-us-south-nyu-wishlist-service-fall2103-prod-20211206-185611") to [prod](https://console.bluemix.net/apps/634ee8f4-02d9-43db-87bc-85b1a686b8ec?env_id=ibm:yp:us-south "ibm:yp:us-south:nyu-wishlist-service-fall2103:prod"), including commit 9573027a887106dedbeb3946fc37b217965111dc
