### ISSUE TITLE
[BDD] - List all wishlists

### ISSUE THREAD

**Issue by ntlz** [devops-wishlist-buddies/wishlists#44]
**As a** developer
**I need** to be able to list all wishlists
**So that** I can see their properties and contents for further requests

Implement frontend to support this part of the API and behavior tests.
Scenario: List all wishlists
```gherkin
Given the following wishlists
| name                  | user_id|
| Birthday Wishlist     | 1 |
| Thanksgiving Wishlist | 1 |
| Apr Wishlist          | 2 |
And the server is running
When I visit the "Home Page"
And I press the "Wishlist_Search" button
Then I should see "Birthday Wishlist" in the results
And I should see "Thanksgiving Wishlist" in the results
And I should see "Apr Wishlist" in the results
```

**Comment by ntlz** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/wishlists-614df33bb025e9001866fedf/issues/devops-wishlist-buddies/wishlists/44?planning-poker) with ZenHub @Fivetoes @jiuliwei @XinyuC97 @yx2512 @ZX-WANG

**Comment by yx2512** [comment]
Added details to the body
