### ISSUE TITLE
Add functionality to add item(s) to a wishlist

### ISSUE THREAD

**Issue by ntlz** [devops-wishlist-buddies/wishlists#5]
**As a** user
**I need** to add item(s) to a wishlist
**So that** I can save items that I wish I could buy in a certain wishlist

**Details & Assumptions:** 
* The selected wishlist must exist
* Each operation can only add several items to one wishlist
* Keep everything local for now (no database)

**Acceptance Criteria:**

```gherkin
Given a set of items and a wishlist
When I hit the "add" API
Then the items will be added to the selected wishlist.
```

**Comment by jiuliwei** [comment]
added more details to the body of this issue

**Comment by ntlz** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/wishlists-614df33bb025e9001866fedf/issues/devops-wishlist-buddies/wishlists/5?planning-poker) with ZenHub @Fivetoes @jiuliwei @XinyuC97 @yx2512 @ZX-WANG

**Comment by ntlz** [comment]
@Fivetoes FYI a piece of code that partially implements this was just merged by @jiuliwei. Review and use/rewrite as convenient to you :)

**Comment by ntlz** [comment]
Request: PUT /wishlists/{wishlist_id}/add-item
Response: {wishlist_id: 123, items: [{...}, ...]} with added item

**Comment by ntlz** [comment]
Ignore me, it was an accident xD
