### ISSUE TITLE
Refactor DELETE logic

### ISSUE THREAD

**Issue by ntlz** [devops-wishlist-buddies/wishlists#54]
1. Add DELETE /wishlists/<wishlist_id>/products/<product_id> to delete an entry in the Product table. 
2. The current DELETE /wishlists/<wishlist_id>/products is fine for convenience. Add empty payload logic to this route: if there is no body with this request, remove all products from the wishlist `wishlist_id`.

**Comment by yx2512** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/27b643c6-9a70-4eea-abde-faef8f7042e9?env_id=ibm:yp:us-south "nyu-wishlist-service-fall2103"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/659061bf-cc38-4631-83b1-de6b76a17d27 "nyu-wishlist-service-fall2103") deployed [wishlists](https://github.com/devops-wishlist-buddies/wishlists/releases/tag/deploy-ibm-yp-us-south-nyu-wishlist-service-fall2103-prod-20211206-185611 "deploy-ibm-yp-us-south-nyu-wishlist-service-fall2103-prod-20211206-185611") to [prod](https://console.bluemix.net/apps/634ee8f4-02d9-43db-87bc-85b1a686b8ec?env_id=ibm:yp:us-south "ibm:yp:us-south:nyu-wishlist-service-fall2103:prod"), including commit b29d3da2241626d277f9862db32cf5abaa013d4d
