### ISSUE TITLE
[BDD] Create a wishlist

### ISSUE THREAD

**Issue by ntlz** [devops-wishlist-buddies/wishlists#76]
**As** a user
**I need** the ability to create a wishlist
**So that** I can save a list of items that I wish I could buy

Implement frontend to support this part of the API and behavior tests.
Scenario: Create a wishlist
```gherkin
Given the server is running
When I visit the "Home Page"
And I set the "Wishlist_Name" to "Jan Wishlist"
And I set the "Wishlist_User_Id" to "1"
And I press the "Create Wishlist" button
Then I should see the "Wishlist_DB_Message" to be "Wishlist Created!"
When I copy the "Wishlist_Id" field
And I press the "Wishlist_Clear" button
Then the "Wishlist_Id" field should be empty
And the "Wishlist_Name" field should be empty
And the "Wishlist_User_Id" field should be empty
When I paste the "Wishlist_Id" field
And I press the "Wishlist_Retrieve" button
Then I should see "Jan Wishlist" in the "Wishlist_Name" field
And I should see "1" in the "Wishlist_User_Id" field
```

**Comment by yx2512** [comment]
Added details to the body.

**Comment by ntlz** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/wishlists-614df33bb025e9001866fedf/issues/devops-wishlist-buddies/wishlists/76?planning-poker) with ZenHub @Fivetoes @jiuliwei @XinyuC97 @yx2512 @ZX-WANG
