### ISSUE TITLE
[BDD] Add a product to wishlist

### ISSUE THREAD

**Issue by ntlz** [devops-wishlist-buddies/wishlists#79]
**As a** user
**I need** to add item(s) to a wishlist
**So that** I can save items that I wish I could buy in a certain wishlist

Implement frontend to support this part of the API and behavior tests.
Scenario: add a product to a wishlist
```gherkin
Given the following wishlists
| name                  | user_id|
| Birthday Wishlist     | 1 |
| Thanksgiving Wishlist | 1 |
| Apr Wishlist          | 2 |
And the server is running
When I visit the "Home Page"
And I set the "Product_Name" to "Toy"
And I set the "Product_price" to "13.2"
And I set the "Product_Status" to "1"
And I set the "Product_Pic_Url" to "www.pic.com/toy.png"
And I set the "Product_Short_Desc" to "this is a toy"
And I set the "Product_Inventory_Id" to "1"
And I set the "Product_Wishlist_Id" to "1"
And I press the "Create_Product" button
Then I should see the "Product_DB_Message" to be "success"
When I copy the "Product_Wishlist_Id" field
And I press the "Product_Clear" button
Then the "Product_Id" field should be empty
And the "Product_Price" field should be empty
And the "Product_Wishlist_Id" field should be empty
When I press the "Wishlist_Clear" button
And I paste the "Wishlist_Id" field
And I press the "Wishlist_Retrieve" button
Then I should see "Birthday Wishlist" in the "Wishlist_Name" field
And I should see "1" in the "Wishlist_User_Id" field
And I should have a "name" field as "Toy" in the "Wishlist_Products" field
```

**Comment by yx2512** [comment]
Added details to the body

**Comment by ntlz** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/wishlists-614df33bb025e9001866fedf/issues/devops-wishlist-buddies/wishlists/79?planning-poker) with ZenHub @Fivetoes @jiuliwei @XinyuC97 @yx2512 @ZX-WANG

**Comment by yx2512** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/27b643c6-9a70-4eea-abde-faef8f7042e9?env_id=ibm:yp:us-south "nyu-wishlist-service-fall2103"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/659061bf-cc38-4631-83b1-de6b76a17d27 "nyu-wishlist-service-fall2103") deployed [wishlists](https://github.com/devops-wishlist-buddies/wishlists/releases/tag/deploy-ibm-yp-us-south-nyu-wishlist-service-fall2103-prod-20211206-185611 "deploy-ibm-yp-us-south-nyu-wishlist-service-fall2103-prod-20211206-185611") to [prod](https://console.bluemix.net/apps/634ee8f4-02d9-43db-87bc-85b1a686b8ec?env_id=ibm:yp:us-south "ibm:yp:us-south:nyu-wishlist-service-fall2103:prod"), including commit fa780ecfbb2fb1887a6254a0f13c8bdef72336c1
