### ISSUE TITLE
[BDD] Edit a product in a wishlist

### ISSUE THREAD

**Issue by ntlz** [devops-wishlist-buddies/wishlists#81]
**As a** developer
**I need** the ability to change product details in a wishlist
**So that** the information can stay up-to-date if there are any updates to product properties

Implement frontend to support this part of the API and behavior tests.
Scenario: Edit a product in a wishlist
```gherkin
Given the following wishlists
|id| name                  | user_id|
|9| Birthday Wishlist     | 1 |
|10| Thanksgiving Wishlist | 1 |
|15| Apr Wishlist          | 2 |

And the following products
|name          |inventory_product_id|price|status|
|IPhone 20      |33                  |1200 |1|
|Board game     |23                  | 30  |1|
|Nintendo Switch|21                  |300  |1|

And the server is running
When I visit the "Home Page"
And enter 9 in the `wishlist_id` field and 1 in the product_id field
And enter 'New and improved IPhone 20' in the product_name field
And enter 'Unavailable' in the product_status field
And press the `Update` button
Then I should see an Ok message
When I press the "Clear" button
And enter 9 in the `wishlist_id` field and 1 in the product_id field
And press the "Search" button
Then I should see 'New and improved IPhone 20' as the name
And I should not see 'Available' as the status
```

**Comment by ntlz** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/wishlists-614df33bb025e9001866fedf/issues/devops-wishlist-buddies/wishlists/81?planning-poker) with ZenHub @Fivetoes @jiuliwei @XinyuC97 @yx2512 @ZX-WANG

**Comment by yx2512** [comment]
I don't think this is within our scope. It's Product team's responsibility to edit any information related to a product. Developers should call whatever api from the Product side to make the modification, instead of calling the api from the wishlist side. @ntlz

**Comment by ntlz** [comment]
@yx2512 what if a product name or availability changes? Since we store a copy of products and don't call the products API every time we need info (otherwise it would require a crazy amount of requests), we need the ability to edit product fields in our database. I was confused as well, but after talking to the professor after sprint 1, he said we basically need CRUD functions for both products and wishlists. This functionality is already supported by the API, and since we're putting a frontend in front of all our endpoints, this should be included as well.

**Comment by XinyuC97** [comment]
I think the logics are weird in all the bdd tests related to products.
If the users want to rename/delete/add a product in/to a wishlist, they need to know the product id and the wishlist id. However, these ids are generated by the system. If we use copy->clear->paste->do something, we can only get one of the two ids.
So I wonder how we can achieve these tests. @ntlz @yx2512

**Comment by ntlz** [comment]
@XinyuC97 hm, good question. I believe we can get away by using just product id. Since it is the primary key in the table, and we return it in the create/get responses, there should be no problem retrieving a product. What do you think?

**Comment by XinyuC97** [comment]
I think this is a good idea to use product id to do those tests.
And I think in the ```Given``` part at the beginning, we can use one table but add a column called products and put a list in that column, which is similar to the  ```result``` part in ```index.html```. There are lists in that list which represents a product.
What do you think?
> @XinyuC97 hm, good question. I believe we can get away by using just product id. Since it is the primary key in the table, and we return it in the create/get responses, there should be no problem retrieving a product. What do you think?

**Comment by ntlz** [comment]
@XinyuC97 I thought we could even have a separate table for columns in `Given`.

**Comment by XinyuC97** [comment]
@ntlz If we have another table, we need to have wishlist_id in that table when the ```Given``` runs. How can we do that?
